FROM golang:1.16-alpine as build

# RUN apk update && apk upgrade && apk add --update alpine-sdk && apk add -no-cache git make cmake 

RUN mkdir /app

WORKDIR /go/src/going_in_circles/go/web-server

RUN pwd
ENV GO111MODULE on
COPY . .
RUN go mod download -x


ADD ./ .


RUN go build -o /web-server

FROM alpine

COPY --from=build /web-server /web-server 

EXPOSE 8000

CMD ["/web-server"]
