// This message is used to notify listeners that a new message has
// arrived from an external client.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: message_transfer_received.proto

package mts

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessageTransferReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientKey               string `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	MessageKey              string `protobuf:"bytes,2,opt,name=message_key,json=messageKey,proto3" json:"message_key,omitempty"`
	Payload                 []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadType             string `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	PayloadSize             int32  `protobuf:"varint,5,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	PayloadFilename         string `protobuf:"bytes,6,opt,name=payload_filename,json=payloadFilename,proto3" json:"payload_filename,omitempty"`
	PayloadTimestampCreated string `protobuf:"bytes,7,opt,name=payload_timestamp_created,json=payloadTimestampCreated,proto3" json:"payload_timestamp_created,omitempty"`
}

func (x *MessageTransferReceived) Reset() {
	*x = MessageTransferReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_transfer_received_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTransferReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTransferReceived) ProtoMessage() {}

func (x *MessageTransferReceived) ProtoReflect() protoreflect.Message {
	mi := &file_message_transfer_received_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTransferReceived.ProtoReflect.Descriptor instead.
func (*MessageTransferReceived) Descriptor() ([]byte, []int) {
	return file_message_transfer_received_proto_rawDescGZIP(), []int{0}
}

func (x *MessageTransferReceived) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *MessageTransferReceived) GetMessageKey() string {
	if x != nil {
		return x.MessageKey
	}
	return ""
}

func (x *MessageTransferReceived) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageTransferReceived) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *MessageTransferReceived) GetPayloadSize() int32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *MessageTransferReceived) GetPayloadFilename() string {
	if x != nil {
		return x.PayloadFilename
	}
	return ""
}

func (x *MessageTransferReceived) GetPayloadTimestampCreated() string {
	if x != nil {
		return x.PayloadTimestampCreated
	}
	return ""
}

var File_message_transfer_received_proto protoreflect.FileDescriptor

var file_message_transfer_received_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6d, 0x74, 0x73, 0x22, 0xa0, 0x02, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a,
	0x19, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x17, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_transfer_received_proto_rawDescOnce sync.Once
	file_message_transfer_received_proto_rawDescData = file_message_transfer_received_proto_rawDesc
)

func file_message_transfer_received_proto_rawDescGZIP() []byte {
	file_message_transfer_received_proto_rawDescOnce.Do(func() {
		file_message_transfer_received_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_transfer_received_proto_rawDescData)
	})
	return file_message_transfer_received_proto_rawDescData
}

var file_message_transfer_received_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_transfer_received_proto_goTypes = []interface{}{
	(*MessageTransferReceived)(nil), // 0: mts.MessageTransferReceived
}
var file_message_transfer_received_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_transfer_received_proto_init() }
func file_message_transfer_received_proto_init() {
	if File_message_transfer_received_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_transfer_received_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTransferReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_transfer_received_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_transfer_received_proto_goTypes,
		DependencyIndexes: file_message_transfer_received_proto_depIdxs,
		MessageInfos:      file_message_transfer_received_proto_msgTypes,
	}.Build()
	File_message_transfer_received_proto = out.File
	file_message_transfer_received_proto_rawDesc = nil
	file_message_transfer_received_proto_goTypes = nil
	file_message_transfer_received_proto_depIdxs = nil
}
