uninstall tiny-vim
install vim

echo "set nocompatible" >> ~/.vimrc


git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go

git clone https://github.com/amix/vimrc.git ~/.vim_runtime


sh ~/.vim_runtime/install_awesome_vimrc.sh
