// this is buyer proto should include all buyer's fields

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: buyer.proto

package order

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Buyer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UaId        string `protobuf:"bytes,1,opt,name=ua_id,json=uaId,proto3" json:"ua_id,omitempty"`        // UA ID
	SiteId      int32  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"` // internal mage site id
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                    // full name
	FirstName   string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone       string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email       string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	CompanyName string `protobuf:"bytes,8,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
}

func (x *Buyer) Reset() {
	*x = Buyer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Buyer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buyer) ProtoMessage() {}

func (x *Buyer) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buyer.ProtoReflect.Descriptor instead.
func (*Buyer) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{0}
}

func (x *Buyer) GetUaId() string {
	if x != nil {
		return x.UaId
	}
	return ""
}

func (x *Buyer) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *Buyer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Buyer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Buyer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Buyer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Buyer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Buyer) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

var File_buyer_proto protoreflect.FileDescriptor

var file_buyer_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x75, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x75, 0x79, 0x65, 0x72, 0x22, 0xd4, 0x01, 0x0a, 0x05, 0x42, 0x75, 0x79, 0x65, 0x72, 0x12, 0x13,
	0x0a, 0x05, 0x75, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x61, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buyer_proto_rawDescOnce sync.Once
	file_buyer_proto_rawDescData = file_buyer_proto_rawDesc
)

func file_buyer_proto_rawDescGZIP() []byte {
	file_buyer_proto_rawDescOnce.Do(func() {
		file_buyer_proto_rawDescData = protoimpl.X.CompressGZIP(file_buyer_proto_rawDescData)
	})
	return file_buyer_proto_rawDescData
}

var file_buyer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_buyer_proto_goTypes = []interface{}{
	(*Buyer)(nil), // 0: buyer.Buyer
}
var file_buyer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buyer_proto_init() }
func file_buyer_proto_init() {
	if File_buyer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buyer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Buyer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buyer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buyer_proto_goTypes,
		DependencyIndexes: file_buyer_proto_depIdxs,
		MessageInfos:      file_buyer_proto_msgTypes,
	}.Build()
	File_buyer_proto = out.File
	file_buyer_proto_rawDesc = nil
	file_buyer_proto_goTypes = nil
	file_buyer_proto_depIdxs = nil
}
