// This message notifies listeners of a change in an order tracking number

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: order_tracking_updated.proto

package order

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderTrackingUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteAbb         string      `protobuf:"bytes,1,opt,name=site_abb,json=siteAbb,proto3" json:"site_abb,omitempty"`
	OrderId         int32       `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ComposedOrderId string      `protobuf:"bytes,3,opt,name=composed_order_id,json=composedOrderId,proto3" json:"composed_order_id,omitempty"` // combines site_abb + order_id
	Status          string      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                            // current updated status
	StatusId        int32       `protobuf:"varint,5,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`                       // current updated status id
	TrackingNumbers []*Tracking `protobuf:"bytes,6,rep,name=tracking_numbers,json=trackingNumbers,proto3" json:"tracking_numbers,omitempty"`   // tracking_numbers is array of tracking, we could have many tracking numbers per order
	Links           []*Link     `protobuf:"bytes,50,rep,name=links,proto3" json:"links,omitempty"`                                             // links is array of link, we could have many services to pull data from
	EventType       string      `protobuf:"bytes,51,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
}

func (x *OrderTrackingUpdated) Reset() {
	*x = OrderTrackingUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tracking_updated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderTrackingUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTrackingUpdated) ProtoMessage() {}

func (x *OrderTrackingUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_order_tracking_updated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTrackingUpdated.ProtoReflect.Descriptor instead.
func (*OrderTrackingUpdated) Descriptor() ([]byte, []int) {
	return file_order_tracking_updated_proto_rawDescGZIP(), []int{0}
}

func (x *OrderTrackingUpdated) GetSiteAbb() string {
	if x != nil {
		return x.SiteAbb
	}
	return ""
}

func (x *OrderTrackingUpdated) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderTrackingUpdated) GetComposedOrderId() string {
	if x != nil {
		return x.ComposedOrderId
	}
	return ""
}

func (x *OrderTrackingUpdated) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderTrackingUpdated) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *OrderTrackingUpdated) GetTrackingNumbers() []*Tracking {
	if x != nil {
		return x.TrackingNumbers
	}
	return nil
}

func (x *OrderTrackingUpdated) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *OrderTrackingUpdated) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type Tracking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"` // tracking number
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // tracking url
}

func (x *Tracking) Reset() {
	*x = Tracking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tracking_updated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracking) ProtoMessage() {}

func (x *Tracking) ProtoReflect() protoreflect.Message {
	mi := &file_order_tracking_updated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracking.ProtoReflect.Descriptor instead.
func (*Tracking) Descriptor() ([]byte, []int) {
	return file_order_tracking_updated_proto_rawDescGZIP(), []int{1}
}

func (x *Tracking) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Tracking) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_order_tracking_updated_proto protoreflect.FileDescriptor

var file_order_tracking_updated_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xaa, 0x02, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69,
	0x74, 0x65, 0x5f, 0x61, 0x62, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69,
	0x74, 0x65, 0x41, 0x62, 0x62, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x2a, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0f, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a,
	0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x32, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75,
	0x74, 0x69, 0x6c, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x33, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x34,
	0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_tracking_updated_proto_rawDescOnce sync.Once
	file_order_tracking_updated_proto_rawDescData = file_order_tracking_updated_proto_rawDesc
)

func file_order_tracking_updated_proto_rawDescGZIP() []byte {
	file_order_tracking_updated_proto_rawDescOnce.Do(func() {
		file_order_tracking_updated_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_tracking_updated_proto_rawDescData)
	})
	return file_order_tracking_updated_proto_rawDescData
}

var file_order_tracking_updated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_tracking_updated_proto_goTypes = []interface{}{
	(*OrderTrackingUpdated)(nil), // 0: order.OrderTrackingUpdated
	(*Tracking)(nil),             // 1: order.tracking
	(*Link)(nil),                 // 2: util.Link
}
var file_order_tracking_updated_proto_depIdxs = []int32{
	1, // 0: order.OrderTrackingUpdated.tracking_numbers:type_name -> order.tracking
	2, // 1: order.OrderTrackingUpdated.links:type_name -> util.Link
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_tracking_updated_proto_init() }
func file_order_tracking_updated_proto_init() {
	if File_order_tracking_updated_proto != nil {
		return
	}
	file_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_order_tracking_updated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderTrackingUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_tracking_updated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tracking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_tracking_updated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_tracking_updated_proto_goTypes,
		DependencyIndexes: file_order_tracking_updated_proto_depIdxs,
		MessageInfos:      file_order_tracking_updated_proto_msgTypes,
	}.Build()
	File_order_tracking_updated_proto = out.File
	file_order_tracking_updated_proto_rawDesc = nil
	file_order_tracking_updated_proto_goTypes = nil
	file_order_tracking_updated_proto_depIdxs = nil
}
