// This message is a command, it commands service to credit a buyer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: order_payment_credit_cmd.proto

package order

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PaymentCreditCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteAbb         string       `protobuf:"bytes,1,opt,name=site_abb,json=siteAbb,proto3" json:"site_abb,omitempty"`
	OrderId         int32        `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ComposedOrderId string       `protobuf:"bytes,3,opt,name=composed_order_id,json=composedOrderId,proto3" json:"composed_order_id,omitempty"` // combines site_abb + order_id
	Origin          *Origin      `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Buyer           *Buyer       `protobuf:"bytes,5,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Unfulfilled     *Unfulfilled `protobuf:"bytes,8,opt,name=unfulfilled,proto3" json:"unfulfilled,omitempty"`
	TotalRefund     float64      `protobuf:"fixed64,9,opt,name=total_refund,json=totalRefund,proto3" json:"total_refund,omitempty"`
	Memo            string       `protobuf:"bytes,10,opt,name=memo,proto3" json:"memo,omitempty"`
	Links           []*Link      `protobuf:"bytes,50,rep,name=links,proto3" json:"links,omitempty"` // links is array of link, we could have many services to pull data from
	EventType       string       `protobuf:"bytes,51,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
}

func (x *PaymentCreditCmd) Reset() {
	*x = PaymentCreditCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_payment_credit_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCreditCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreditCmd) ProtoMessage() {}

func (x *PaymentCreditCmd) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_credit_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreditCmd.ProtoReflect.Descriptor instead.
func (*PaymentCreditCmd) Descriptor() ([]byte, []int) {
	return file_order_payment_credit_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentCreditCmd) GetSiteAbb() string {
	if x != nil {
		return x.SiteAbb
	}
	return ""
}

func (x *PaymentCreditCmd) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentCreditCmd) GetComposedOrderId() string {
	if x != nil {
		return x.ComposedOrderId
	}
	return ""
}

func (x *PaymentCreditCmd) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PaymentCreditCmd) GetBuyer() *Buyer {
	if x != nil {
		return x.Buyer
	}
	return nil
}

func (x *PaymentCreditCmd) GetUnfulfilled() *Unfulfilled {
	if x != nil {
		return x.Unfulfilled
	}
	return nil
}

func (x *PaymentCreditCmd) GetTotalRefund() float64 {
	if x != nil {
		return x.TotalRefund
	}
	return 0
}

func (x *PaymentCreditCmd) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *PaymentCreditCmd) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *PaymentCreditCmd) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_order_payment_credit_cmd_proto protoreflect.FileDescriptor

var file_order_payment_credit_cmd_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x62, 0x75, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf0, 0x02, 0x0a, 0x10, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x61,
	0x62, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x41, 0x62,
	0x62, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x22,
	0x0a, 0x05, 0x62, 0x75, 0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x62, 0x75, 0x79, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x79, 0x65, 0x72, 0x52, 0x05, 0x62, 0x75, 0x79,
	0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x75, 0x6e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x55, 0x6e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x52,
	0x0b, 0x75, 0x6e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x65, 0x6d, 0x6f, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x32, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_payment_credit_cmd_proto_rawDescOnce sync.Once
	file_order_payment_credit_cmd_proto_rawDescData = file_order_payment_credit_cmd_proto_rawDesc
)

func file_order_payment_credit_cmd_proto_rawDescGZIP() []byte {
	file_order_payment_credit_cmd_proto_rawDescOnce.Do(func() {
		file_order_payment_credit_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_payment_credit_cmd_proto_rawDescData)
	})
	return file_order_payment_credit_cmd_proto_rawDescData
}

var file_order_payment_credit_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_payment_credit_cmd_proto_goTypes = []interface{}{
	(*PaymentCreditCmd)(nil), // 0: order.PaymentCreditCmd
	(*Origin)(nil),           // 1: util.Origin
	(*Buyer)(nil),            // 2: buyer.Buyer
	(*Unfulfilled)(nil),      // 3: inventory.Unfulfilled
	(*Link)(nil),             // 4: util.Link
}
var file_order_payment_credit_cmd_proto_depIdxs = []int32{
	1, // 0: order.PaymentCreditCmd.origin:type_name -> util.Origin
	2, // 1: order.PaymentCreditCmd.buyer:type_name -> buyer.Buyer
	3, // 2: order.PaymentCreditCmd.unfulfilled:type_name -> inventory.Unfulfilled
	4, // 3: order.PaymentCreditCmd.links:type_name -> util.Link
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_payment_credit_cmd_proto_init() }
func file_order_payment_credit_cmd_proto_init() {
	if File_order_payment_credit_cmd_proto != nil {
		return
	}
	file_util_proto_init()
	file_buyer_proto_init()
	file_inventory_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_order_payment_credit_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCreditCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_payment_credit_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_payment_credit_cmd_proto_goTypes,
		DependencyIndexes: file_order_payment_credit_cmd_proto_depIdxs,
		MessageInfos:      file_order_payment_credit_cmd_proto_msgTypes,
	}.Build()
	File_order_payment_credit_cmd_proto = out.File
	file_order_payment_credit_cmd_proto_rawDesc = nil
	file_order_payment_credit_cmd_proto_goTypes = nil
	file_order_payment_credit_cmd_proto_depIdxs = nil
}
